name: Terraform Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Replace with your desired Terraform version

      - name: Initialize Terraform
        run: |
          cd terraform  # Change directory to your Terraform code directory
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan 

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
